import React from 'react'

export default function SummaryView({ summary }) {
  if (!summary) {
    return (
      <div className="bg-gray-100 rounded-lg p-6 text-gray-500">
        <p>No summary available</p>
      </div>
    )
  }

  return (
    <div className="bg-white rounded-lg shadow p-6">
      <div className="mb-4 pb-4 border-b">
        <span className="inline-block bg-blue-100 text-blue-800 text-xs font-semibold px-3 py-1 rounded-full">
          {summary.style || 'NEWS_ANCHOR'}
        </span>
      </div>
      <div className="prose prose-sm max-w-none">
        <p className="text-gray-700 leading-relaxed">{summary.content}</p>
      </div>
      {summary.model_used && (
        <div className="mt-4 pt-4 border-t text-xs text-gray-500">
          <p>Generated by: {summary.model_used}</p>
          {summary.tokens_used && <p>Tokens used: {summary.tokens_used}</p>}
        </div>
      )}
    </div>
  )
}